# Playbook to allocate host variables to all hosts in the inventory. This is currently only
# needed to build the ansible_host host variables from the configured subnet and host_address.
# This playbook should be included in all others.
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: Jul/30/2020
# -------------------------------------------------------------------------------------------------
- hosts: localhost
  connection: local
  name: Allocate host variables
  vars_files:
    - "{{ playbook_dir }}/strings.yml"
  tasks:
    - add_host:
        name: "{{ item }}"
      args:
        # For now assuming all IPs are in the internal subnet
        ansible_host: "{{ network_subnet | ansible.netcommon.ipmath(hostvars[item]['host_address']) }}"
      no_log: True
      loop: "{{ groups['windows'] | union(groups['linux']) }}"
