# Playbook to create Windows OS template. For simplicity, you can oversize hardware
# requirements to ensure a single template can be used for all applications.
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: May/27/2020
# -------------------------------------------------------------------------------------------------
- hosts: localhost
  connection: local
  name: Create Windows operating system templates
  vars_files:
    - "{{ playbook_dir }}/vault.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  tasks:
    - name: Create Windows Server 2019 Template
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        folder: "{{ workload_folder }}"
        name: "{{ template_win_2019 }}"
        state: present
        guest_id: windows9Server64Guest
        hardware:
          memory_mb: 8192
          num_cpus: 2
          num_cpu_cores_per_socket: 1
          version: 14
          scsi: lsilogicsas
          boot_firmware: efi
        disk:
          - size_gb: 100
            type: thin
            datastore: "{{ workload_datastore }}"
        cdrom:
          - controller_type: sata
            controller_number: 0
            unit_number: 0
            type: iso
            iso_path: "{{ iso_win_2019 }}"
          - controller_type: sata
            controller_number: 0
            unit_number: 1
            type: iso
            iso_path: "{{ iso_bootstrap }}"
        customization:
          # Riyadh timezone
          timezone: 150
          password: "{{ win_local_password }}"
          orgname: "{{ orgname }}"
        networks:
          - name: "{{ network_name }}"
            type: dhcp
        resource_pool: "{{ resource_pool }}"
      register: create_win_2019_template

    - name: Change boot order to cdrom
      vmware_guest_boot_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        name: "{{ template_win_2019 }}"
        boot_order:
          - cdrom
          - disk
          - ethernet
      register: win_boot_order

    - name: Add USB 3.1 controller
      vmware_guest_controller:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        name: "{{ template_win_2019 }}"
        controllers:
          - state: present
            type: usb3

    - name: Power on Windows template after configuration complete
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        name: "{{ template_win_2019 }}"
        state: poweredon
