# Playbook to create Linux OS template. For simplicity, you can oversize hardware
# requirements to ensure a single template can be used for all applications.
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: Jun/02/2020
# -------------------------------------------------------------------------------------------------
- hosts: localhost
  connection: local
  name: Create Linux operating system templates
  vars_files:
    - "{{ playbook_dir }}/vault.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  tasks:
    - name: Create Centos 8 Template
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        folder: "{{ workload_folder }}"
        name: "{{ template_centos_8 }}"
        state: present
        guest_id: centos8_64Guest
        hardware:
          memory_mb: 8192
          num_cpus: 2
          num_cpu_cores_per_socket: 1
          version: 14
          scsi: lsilogicsas
          boot_firmware: efi
        disk:
          - size_gb: 100
            type: thin
            datastore: "{{ workload_datastore }}"
        cdrom:
          - controller_type: sata
            controller_number: 0
            unit_number: 0
            type: iso
            iso_path: "{{ iso_paths['centos_8'] }}"
          - controller_type: sata
            controller_number: 0
            unit_number: 1
            type: iso
            iso_path: "{{ iso_paths['bootstrap_centos'] }}"
        customization:
          timezone: "Asia/Riyadh"
          password: "{{ linux_local_password }}"
          orgname: "{{ orgname }}"
        networks:
          - name: "{{ network_name }}"
            type: dhcp
        resource_pool: "{{ resource_pool }}"
      register: create_centos_8_template

    - name: Add USB 3.1 controller
      community.vmware.vmware_guest_controller:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        name: "{{ template_centos_8 }}"
        controllers:
          - state: present
            type: usb3

    - name: Power on Linux template after configuration complete
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        name: "{{ template_centos_8 }}"
        state: poweredon
        wait_for_ip_address: yes
        # Wait 15 minutes for template to be prepared
        wait_for_ip_address_timeout: 900

    - name: Shut down Linux template OS after its prepared
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        name: "{{ template_centos_8 }}"
        state: shutdownguest
        # Wait 2 minutes for shutdown to complete
        state_change_timeout: 120

    - name: Remove second CD drive and unmount installation disc
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        name: "{{ template_centos_8 }}"
        state: present
        is_template: yes
        cdrom:
          - controller_type: sata
            controller_number: 0
            unit_number: 0
            type: client
          - controller_type: sata
            controller_number: 0
            unit_number: 1
            state: absent
