# Playbook to deploy all inventory servers, leaving any configuration to the corresponding
# server-specific playbook. For now, all servers of a particular OS will have the same hardware
# specs. TODO: add server-specific specs to the inventory variables.
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: May/25/2020
# -------------------------------------------------------------------------------------------------
- import_playbook: allocate_host_variables.yml

- hosts: all
  connection: local
  name: Create Infrastructure Servers
  vars_files:
    - "{{ playbook_dir }}/vault.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  tasks:
    - name: Create Windows virtual machines
      vars:
        computer_name: "{{ inventory_hostname }}"
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        folder: "{{ workload_folder }}"
        name: "{{ userid }}-{{ inventory_hostname }}"
        state: poweredon
        template: "{{ ('desktops' in group_names) | ternary(template_win_10, template_win_2019) }}"
        hardware:
          memory_mb: 8192
          num_cpus: 2
          num_cpu_cores_per_socket: 1
          version: 14
        customization: "{{ custom_win_2019_workgroup }}"
        networks:
          - name: "{{ network_name }}"
            type: static
            ip: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
            netmask: "{{ network_mask }}"
            gateway: "{{ network_gateway }}"
        resource_pool: "{{ resource_pool }}"
        wait_for_ip_address: yes
        wait_for_customization: yes
      register: create_windows_server
      when: "'windows' in group_names"
      delegate_to: localhost

    - name: Create Linux virtual machines
      vars:
        computer_name: "{{ inventory_hostname }}"
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        folder: "{{ workload_folder }}"
        name: "{{ userid }}-{{ inventory_hostname }}"
        state: poweredon
        template: "{{ template_centos_8 }}"
        customization: "{{ custom_centos_8 }}"
        networks:
          - name: "{{ network_name }}"
            type: static
            ip: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
            netmask: "{{ network_mask }}"
            gateway: "{{ network_gateway }}"
        resource_pool: "{{ resource_pool }}"
        wait_for_ip_address: yes
        wait_for_customization: yes
      register: create_linux_server
      when: "'linux' in group_names"
      delegate_to: localhost

    - name: Mount iso files where needed
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        name: "{{ userid }}-{{ inventory_hostname }}"
        state: present
        cdrom:
          - controller_type: sata
            controller_number: 0
            unit_number: 0
            type: iso
            iso_path: "{{ iso_paths[hostvars[inventory_hostname]['mount_iso']] }}"
      when: "{{ hostvars[inventory_hostname]['mount_iso'] is defined }}"
      delegate_to: localhost
