# Includes the create_windows_template tasks to create templates for both Windows Server 2019
# and Windows 10 without duplicate work.
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: Sep/08/2020
# -------------------------------------------------------------------------------------------------
- hosts: localhost
  connection: local
  name: Create Windows operating system templates
  vars_files:
    - "{{ playbook_dir }}/vault.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  tasks:
  - include_tasks: create_windows_template.yml
    vars:
      template_name: "{{ template_win_2019 }}"
      template_friendly_name: "Windows Server 2019"
      template_guest_id: windows9Server64Guest
      installer_path: "{{ iso_paths['win_2019'] }}"
      bootstrap_path: "{{ iso_paths['bootstrap'] }}"
      template_hostname: "{{ userid }}-windows-server-template"
  - include_tasks: create_windows_template.yml
    vars:
      template_name: "{{ template_win_10 }}"
      template_friendly_name: "Windows Server 2019"
      template_guest_id: windows9Server64Guest
      installer_path: "{{ iso_paths['win_10'] }}"
      bootstrap_path: "{{ iso_paths['bootstrap_win_10'] }}"
      template_hostname: "{{ userid }}-windows-server-template"
