# Playbook to deploy all OVF appliances
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: May/11/2021
# -------------------------------------------------------------------------------------------------
- import_playbook: allocate_host_variables.yml

- hosts: localhost
  connection: local
  name: Deploy OVF appliances
  vars_files:
    - "{{ playbook_dir }}/vault.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  tasks:
    - name: Create Windows virtual machines
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        resource_pool: "{{ resource_pool }}"
        folder: "{{ workload_folder }}"
