# Playbook to deploy all inventory servers, leaving any configuration to the corresponding
# server-specific playbook. For now, all servers of a particular OS will have the same hardware
# specs. TODO: add server-specific specs to the inventory variables.
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: May/25/2020
# -------------------------------------------------------------------------------------------------
- import_playbook: allocate_host_variables.yml
- import_playbook: create_network.yml

- hosts: all
  connection: local
  name: Create Infrastructure Servers
  vars_files:
    - "{{ playbook_dir }}/vault.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  tasks:
    - name: Create all virtual machines
      community.aws.ec2_instance:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ aws_region }}"
        key_name: ws1-lab
        instance_type: "{{ ('windows' in group_names) | ternary('t3.xlarge', 't3.large') }}"
        image_id: "{{ ('windows' in group_names) | ternary(windows_ami, linux_ami) }}"
        wait: yes
        name: "{{ userid }}-{{ inventory_hostname }}"
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_size: 100
              volume_type: gp3
              delete_on_termination: yes
        vpc_subnet_id: "{{ hostvars['localhost']['create_subnet'].subnet.id }}"
        network:
          assign_public_ip: no
          delete_on_termination: yes
          private_ip_address: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
      register: create_server
      when: "'windows' in group_names or 'linux' in group_names"
      delegate_to: localhost

    - name: Get all administrator passwords into memory
      community.aws.ec2_win_password:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ aws_region }}"
        key_file: "~/aws-creds/ws1-lab.pem"
        wait: yes
      register: win_local_password
