# Playbook to configure all SQL Servers
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: May/29/2020
# -------------------------------------------------------------------------------------------------
- hosts: databases
  name: Configure SQL Servers
  vars_files:
    - "{{ playbook_dir }}/passwords.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  vars:
    ansible_connection: winrm
    ansible_user: Administrator
    ansible_password: "{{ win_local_password }}"
    ansible_winrm_transport: ntlm
    ansible_port: 5985
  tasks:
    - name: Get disk facts
      win_disk_facts:
    - name: Install SQL Server from mounted ISO
      debug:
        msg: "Item is: {{ item }}"
      loop: "{{ ansible_facts.disks }}"
