# Playbook to configure all SQL Servers
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: May/29/2020
# -------------------------------------------------------------------------------------------------
- hosts: databases
  name: Configure SQL Servers
  vars_files:
    - "{{ playbook_dir }}/passwords.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  vars:
    ansible_connection: winrm
    ansible_user: Administrator
    ansible_password: "{{ win_local_password }}"
    ansible_winrm_transport: ntlm
    ansible_port: 5985
  tasks:
    - name: Get disk facts
      win_shell: Get-CimInstance Win32_LogicalDisk | ?{ $_.DriveType -eq 5 -and $_.VolumeName -eq 'SqlSetup_x64_ENU' } | % {$_.DeviceID}
      register: drive_output

    - name: Join server to domain
      win_domain_membership:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: "{{ domain_admin_user }}"
        domain_admin_password: "{{ domain_admin_password }}"
        domain_ou_path: "{{ 

    - name: Install SQL Server from mounted ISO
      win_shell: |
        D:\setup.exe /IACCEPTSQLSERVERLICENSETERMS /ACTION="Install"
        /FEATURES=SQLEngine,Replication,Conn /INSTANCENAME="HARAMCODB"
        /SQLSYSADMINACCOUNTS="Administrator,Haramco\Administrator"
        /SQLCOLLATION="Latin1_General_CI_AS" /qs
