# Playbook to destroy all VMs in the inventory.
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: Aug/03/2020
# -------------------------------------------------------------------------------------------------
- import_playbook: allocate_host_variables.yml

- hosts: all
  connection: local
  name: Delete Infrastructure Servers
  vars_files:
    - "{{ playbook_dir }}/vault.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  tasks:
    - name: Delete Windows and Linux machines
      community.aws.ec2_instance:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ aws_region }}"
        name: "{{ userid }}-{{ inventory_hostname }}"
        state: absent
      when: "'windows' in group_names or 'linux' in group_names"
      delegate_to: localhost
