# Playbook to destroy all VMs in the inventory.
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: Aug/03/2020
# -------------------------------------------------------------------------------------------------
- import_playbook: allocate_host_variables.yml

- hosts: localhost
  connection: local
  name: Delete Infrastructure Servers
  vars_files:
    - "{{ playbook_dir }}/vault.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  tasks:
    - name: Delete Windows and Linux machines
      amazon.aws.ec2:
        exact_count: 0
        count_tag:
          name: "{{ userid }}-{{ inventory_hostname }}"
        state: absent
      loop: "{{ groups['windows:&linux'] }}"
