# Playbook to prepare the API automation service. This is only used to provide
# an API to the other playbooks.
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: Jul/24/2021
# -------------------------------------------------------------------------------------------------
- import_playbook: allocate_host_variables.yml

- hosts: django
  name: Install pre-requisites and rundeck
  vars_files:
    - "{{ playbook_dir }}/vault.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  vars:
    ansible_user: root
    ansible_password: "{{ linux_local_password }}"
  tasks:
    # TODO: should this be in the image?
    - name: Install python
      dnf:
        name: python3
        state: present

    - name: Install git
      dnf:
        name: git-all
        state: present

    - name: Create project directory
      file:
        path: /rest_api
        state: directory
        mode: '0755'

    - name: Install virtualenv
      pip:
        name: virtualenv

    - name: Install Django into virtual env
      pip:
        name: Django
        virtualenv: /rest_api/venv

    - name: Install paramiko into virtual env
      pip:
        name: paramiko
        virtualenv: /rest_api/venv

    - name: Install Django Rest Framework into virtual env
      pip:
        name: djangorestframework
        virtualenv: /rest_api/venv

    - name: Install Django OAuth toolkit
      pip:
        name: django-oauth-toolkit
        virtualenv: /rest_api/venv

    - firewalld:
        service: https
        permanent: yes
        immediate: yes
        state: enabled
        zone: public
