# Playbook to configure the DNS Server with all needed DNS records. DNS records that correspond to
# domain-joined Windows hosts need not be created here, since they are automatically created by
# Active Directory when the hosts are joined.
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: Jun/16/2020
# -------------------------------------------------------------------------------------------------
- hosts: "{{ groups['domain_controllers'] | random }}"
  name: Configure private DNS records
  vars_files:
    - "{{ playbook_dir }}/vault.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  tasks:
    - win_dns_record:
        name: "uem"
        type: "A"
        value: "{{ virtual_ips[uem_console] }}"
    - win_dns_record:
        name: "uds"
        type: "A"
        value: "{{ virtual_ips[uem_ds] }}"
    - name: Exchange internal FQDN
      win_dns_record:
        name: "mail"
        type: "A"
        # TODO: for now just point to our only load balancer; revise later
        value: "{{ network_subnet }}.{{ hostvars['"
    - win_dns_record:
        name: "pki"
        type: "A"
        value: "{{ network_subnet }}.60"

    #- name: Exchange MX record
      #win_dns_record:
        #name: 
- hosts: localhost
  name: Create public DNS records
  tasks:
    - name: UAGR
      community.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: uagr.{{ domain_name }}
        value: "{{ public_ip_uagr }}"

    - name: UEM Device Services
      community.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: uds.{{ domain_name }}
        value: "{{ public_ip_uem }}"

    - name: Email Notification Service
      community.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: ens.{{ domain_name }}
        value: "{{ public_ip_uem }}"

    - name: Secure Email Gateway
      community.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: seg.{{ domain_name }}
        value: "{{ public_ip_uem }}"
