# Playbook to configure the DNS Server with all needed DNS records
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: Jun/16/2020
# -------------------------------------------------------------------------------------------------
- hosts: "{{ groups['domain_controllers'] | random }}"
  name: Configure domain name server
  vars_files:
    - "{{ playbook_dir }}/vault.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  tasks:
    - name: Workspace ONE Console
      win_dns_record:
        name: "uemc"
        type: "A"
        value: "{{ hostvars['uemc01']['ansible_host'] }}"
      win_dns_record:
        name: "uds"
        type: "A"
        value: "{{ hostvars['uds01']['ansible_host'] }}"
      win_dns_record:
        name: "uds"
        type: "A"
        value: "{{ hostvars['uds01']['ansible_host'] }}"
    - name: Exchange internal FQDN
      win_dns_record:
        name: "mail"
        type: "A"
        # TODO: for now just point to our only load balancer; revise later
        value: "{{ network_subnet}}.60"

    #- name: Exchange MX record
      #win_dns_record:
        #name: 
