# Playbook to configure the needed Active Directory structure
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: May/30/2020
# -------------------------------------------------------------------------------------------------
- import_playbook: allocate_host_variables.yml

- hosts: domain_controllers
  name: Create domain users
  vars_files:
    - "{{ playbook_dir }}/vault.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  vars:
    ansible_connection: winrm
    ansible_user: Administrator
    ansible_password: "{{ win_local_password }}"
    ansible_winrm_transport: ntlm
    ansible_port: 5985
    organizational_units:
      - "{{ server_ou }}"
      - "{{ exchange_ou }}"
      - "{{ account_ou }}"
      - "{{ workstation_ou }}"
      - "{{ user_ou }}"
      - "{{ group_ou }}"
      - "{{ service_ou }}"
      - "{{ horizon_desktop_ou }}"
      - "{{ horizon_rdsh_ou }}"
  tasks:
    - name: Install DSC module for Active Directory
      win_psmodule:
        name: ActiveDirectoryDsc
        state: present

    - name: Create domain OUs
      win_dsc:
        resource_name: ADOrganizationalUnit
        Name: '{{ item | regex_replace("^[^=]+?=([^,]+),(.*)", "\1") }}'
        Path: '{{ item | regex_replace("^[^,]+?,(.*)", "\1") }}'
        ProtectedFromAccidentalDeletion: no
        Ensure: Present
      run_once: yes
      loop: "{{ organizational_units }}"

    - win_domain_user:
        name: jdoe
        firstname: John
        surname: Doe
        company: "{{ orgname }}"
        password: "{{ domain_user_password }}"
      run_once: yes

    - win_domain_user:
        name: eblofeld
        firstname: Ernst
        surname: Blofeld
        company: "{{ orgname }}"
        password: "{{ domain_user_password }}"
      run_once: yes

    - win_domain_user:
        name: alectrev
        firstname: Alec
        surname: Trevelyan
        company: "{{ orgname }}"
        password: "{{ domain_user_password }}"
      run_once: yes

    - win_domain_user:
        name: goldfinger
        firstname: Auric
        surname: Goldfinger
        company: "{{ orgname }}"
        password: "{{ domain_user_password }}"
      run_once: yes

    - win_domain_user:
        name: elargo
        firstname: Emilio
        surname: Largo
        company: "{{ orgname }}"
        password: "{{ domain_user_password }}"
      run_once: yes

    - win_domain_user:
        name: dbsvc
        password: "{{ domain_user_password }}"
        path: "{{ service_ou }}"
      run_once: yes

    - name: Account to clone Horizon virtual desktops and RDSH machines
      win_domain_user:
        name: horizoncloner
        password: "{{ domain_user_password }}"
        path: "{{ service_ou }}"
      run_once: yes

    - name: Grant Horizon clone account permissions to create computer objects in virtual desktop OU
      win_dsc:
        resource_name: ADObjectPermissionEntry
        Path: "{{ horizon_desktop_ou }}"
        IdentityReference: "{{ domain_first_name }}\\horizoncloner"
        ActiveDirectoryRights:
          - CreateChild
          - DeleteChild
        ObjectType: 'bf967aba-0de6-11d0-a285-00aa003049e2' # Computer Object type GUID
        InheritedObjectType: '00000000-0000-0000-0000-000000000000'
        ActiveDirectorySecurityInheritance: All
        AccessControlType: Allow
      run_once: yes

    - name: Grant Horizon clone account permissions to Read/Write properties in virtual desktop OU
      win_dsc:
        resource_name: ADObjectPermissionEntry
        Path: "{{ horizon_desktop_ou }}"
        IdentityReference: "{{ domain_first_name }}\\horizoncloner"
        ActiveDirectoryRights:
          - ReadProperty
          - WriteProperty
        InheritedObjectType: 'bf967aba-0de6-11d0-a285-00aa003049e2' # Computer Object type GUID
        ObjectType: '00000000-0000-0000-0000-000000000000'
        ActiveDirectorySecurityInheritance: Descendents
        AccessControlType: Allow
      run_once: yes

    - name: Grant Horizon clone account permissions to reset passwords in virtual desktop OU
      win_dsc:
        resource_name: ADObjectPermissionEntry
        Path: "{{ horizon_desktop_ou }}"
        IdentityReference: "{{ domain_first_name }}\\horizoncloner"
        ActiveDirectoryRights:
          - ExtendedProperty
        InheritedObjectType: 'bf967aba-0de6-11d0-a285-00aa003049e2' # Computer Object type GUID
        ObjectType: '00299570-246d-11d0-a768-00aa006e0529'
        ActiveDirectorySecurityInheritance: Descendents
        AccessControlType: Allow
      run_once: yes
