# Playbook to configure the needed Active Directory structure
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: May/30/2020
# -------------------------------------------------------------------------------------------------
- hosts: localhost
  connection: local
  name: Configure domain structure
  vars_files:
    - "{{ playbook_dir }}/passwords.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  vars:
    organizational_units:
      - "{{ server_ou }}"
      - "{{ exchange_ou }}"
      - "{{ account_ou }}"
      - "{{ workstation_ou }}"
      - "{{ user_ou }}"
      - "{{ group_ou }}"
  tasks:
    - name: Create Domain OUs
      ldap_entry:
        dn: "{{ item }}"
        objectClass: organizationalUnit
        server_uri: "ldap://{{ domain_name }}/"
        bind_dn: "{{ domain_admin_dn }}"
        bind_pw: "{{ domain_admin_password }}"
      loop: "{{ organizational_units }}"

- hosts: domain_controllers
  name: Create domain users
  vars_files:
    - "{{ playbook_dir }}/passwords.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  vars:
    ansible_connection: winrm
    ansible_user: Administrator
    ansible_password: "{{ win_local_password }}"
    ansible_winrm_transport: ntlm
    ansible_port: 5985
  tasks:
    - win_domain_user:
        name: jdoe
        firstname: John
        surname: Doe
        company: "{{ orgname }}"
        password: "{{ domain_user_password }}"
      run_once: yes

    - win_domain_user:
        name: eblofeld
        firstname: Ernst
        surname: Blofeld
        company: "{{ orgname }}"
        password: "{{ domain_user_password }}"
      run_once: yes

    - win_domain_user:
        name: alectrev
        firstname: Alec
        surname: Trevelyan
        company: "{{ orgname }}"
        password: "{{ domain_user_password }}"
      run_once: yes

    - win_domain_user:
        name: goldfinger
        firstname: Auric
        surname: Goldfinger
        company: "{{ orgname }}"
        password: "{{ domain_user_password }}"
      run_once: yes

    - win_domain_user:
        name: elargo
        firstname: Emilio
        surname: Largo
        company: "{{ orgname }}"
        password: "{{ domain_user_password }}"
      run_once: yes
