# Playbook to deploy servers and configure them as domain controllers
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: May/25/2020
# -------------------------------------------------------------------------------------------------
- hosts: localhost
  connection: local
  name: Create Active Directory servers
  vars:
    computer_name: "haudahh"
  vars_files:
    - "{{ playbook_dir }}/passwords.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  tasks:
    - name: Create AD virtual machines
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        folder: "{{ workload_folder }}"
        name: "{{ item.name }}"
        state: poweredon
        guest_id: windows9Server64Guest
        template: "{{ template_win_2019 }}"
        hardware:
          memory_mb: 8192
          num_cpus: 1
          num_cpu_cores_per_socket: 1
          version: 14
        customization: "{{ custom_win_2019_workgroup }}"
        networks:
          - name: "{{ network_name }}"
            type: static
            ip: "{{ item.ip }}"
            netmask: "{{ network_mask }}"
            gateway: "{{ network_gateway }}"
        resource_pool: "{{ resource_pool }}"
        wait_for_ip_address: yes
        wait_for_customization: yes
      register: deploy_ad
      loop:
        - { name: 'haudah-dc01', ip: '192.168.77.50' }
          #- { name: 'haudah-dc02', ip: '192.168.77.51' }

    #- name: Configure AD servers
