# Playbook to configure all Active Directory domain controllers
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: May/26/2020
# -------------------------------------------------------------------------------------------------
- hosts: domain_controllers
  name: Configure Domain Controller Servers
  vars_files:
    - "{{ playbook_dir }}/passwords.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  vars:
    ansible_connection: winrm
    ansible_user: Administrator
    ansible_password: "{{ win_local_password }}"
    ansible_winrm_transport: ntlm
    ansible_port: 5985
  tasks:
    - name: Install first domain controller if domain does not exist
      ansible.windows.win_domain:
        create_dns_delegation: no
        dns_domain_name: "{{ domain_name }}"
        safe_mode_password: "{{ domain_recovery_password }}"
      register: create_domain

    - name: Reboot new domain controller
      win_reboot:
      when: create_domain.reboot_required

    - name: Install domain controller in an existing domain
      ansible.windows.win_domain_controller:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: "{{ domain_admin_user }}@{{ domain_name }}"
        domain_admin_password: "{{ domain_admin_password }}"
        safe_mode_password: "{{ domain_recovery_password }}"
        state: domain_controller
      register: join_domain

    - name: Reboot new domain controller (existing domain)
      win_reboot:
      when: join_domain.reboot_required
