# Playbook to create all CIFS, DFS, and NFS file shares needed in the environment
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: Jun/24/2020
# -------------------------------------------------------------------------------------------------
- hosts: windows:&file_shares
  name: Prepare Windows file share servers
  vars_files:
    - "{{ playbook_dir }}/passwords.yml"
    - "{{ playbook_dir }}/strings.yml"
  vars:
    ansible_connection: winrm
    ansible_user: Administrator
    ansible_password: "{{ win_local_password }}"
    ansible_winrm_transport: ntlm
    ansible_port: 5985
  tasks:
    - include_tasks: join_domain.yml
      vars:
        machine_ou: "{{ server_ou }}"

    - name: Create directories for file shares
      win_file:
        path: C:\shares\{{ item.path }}
        state: directory
      loop: "{{ win_shared_folders }}"

    - win_share:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        path: C:\shares\{{ item.path }}
        full: "{{ item.full }}"
      when: not item.cluster
      loop: "{{ win_shared_folders }}"

    - name: Populate shares with web files
      win_get_url:
        url: "{{ item[0].url }}"
        dest: C:\shares\{{ item[1].path }}
      when: item[0].share == item[1].name
      # perform Cartesian product then filter out invalid pairs
      loop: "{{ share_downloads | product(win_shared_folders) | list }}"
