# Playbook to configure Horizon Connection servers
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: May/21/2021
# -------------------------------------------------------------------------------------------------
- import_playbook: allocate_host_variables.yml

- hosts: horizon_connection_servers
  name: Join Connection Servers to domain
  vars_files:
    - "{{ playbook_dir }}/vault.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  vars:
    ansible_connection: winrm
    ansible_user: Administrator
    ansible_password: "{{ win_local_password }}"
    ansible_winrm_transport: ntlm
    ansible_port: 5985
  tasks:
    - include_tasks: join_domain.yml
      vars:
        machine_ou: "{{ server_ou }}"

- hosts: horizon_connection_servers
  name: Join Connection Servers to domain
  vars_files:
    - "{{ playbook_dir }}/vault.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  vars:
    ansible_connection: winrm
    ansible_user: Administrator@{{ domain_name }}
    ansible_password: "{{ domain_admin_password }}"
    ansible_winrm_transport: credssp
    ansible_port: 5985
  tasks:
    - name: Create folder for installers
      win_file:
        path: C:\Installers
        state: directory

    - name: Copy installers
      win_copy:
        src: \\{{ domain_name }}\Shares\domain\{{ item }}
        dest: C:\Installers\{{ item }}
        remote_src: yes
      loop:
        - horizon-8.2.exe

    - name: Get current user (domain admin) SID
      win_shell: |
        ([System.Security.Principal.WindowsIdentity]::GetCurrent()).User.Value
      register: usersid
      changed_when: "'S-1' not in usersid.stdout"

    - name: Install primary Horizon Connection Server
      win_package:
        path: C:\Installers\horizon-8.2.exe
        product_id: '{203F3FCC-0874-49DE-9A40-661A92A1A713}'
        arguments: /s /v"/qn VDM_SERVER_INSTANCE_TYPE=1 VDM_INITIAL_ADMIN_SID={{ usersid.stdout | trim }} VDM_SERVER_RECOVERY_PWD={{ horizon_recovery_password }}"
        state: "present"
      when: inventory_hostname == "{{ groups['horizon_connection_servers'] | first }}"

    - name: Install replica Horizon Connection Server
      win_package:
        path: C:\Installers\horizon-8.2.exe
        product_id: '{203F3FCC-0874-49DE-9A40-661A92A1A713}'
        arguments: /s /v"/qn VDM_SERVER_INSTANCE_TYPE=2 ADAM_PRIMARY_NAME={{ groups['horizon_connection_servers'] | first }}.{{ domain_name }} VDM_INITIAL_ADMIN_SID={{ usersid.stdout | trim }}"
        state: "present"
      when: inventory_hostname != "{{ groups['horizon_connection_servers'] | first }}"
