# Playbook to configure HAProxy load balancers
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: Jun/02/2020
# -------------------------------------------------------------------------------------------------
- import_playbook: allocate_host_variables.yml

- hosts: haudah-lb01
  name: Create and configure the HAProxy load balancer
  vars_files:
    - "{{ playbook_dir }}/vault.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  vars:
    ansible_user: root
    ansible_password: "{{ linux_local_password }}"
  tasks:
    - firewalld:
        service: https
        permanent: yes
        state: enabled
        zone: public

    - firewalld:
        service: http
        permanent: yes
        state: enabled
        zone: public

    - firewalld:
        service: https
        permanent: yes
        state: enabled
        zone: public

    - name: Install HAProxy
      dnf:
        name: haproxy
        state: present

    - name: Transfer HAProxy config
      template:
        src: configurations/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg

    - name: Create merged certificate private key files
      shell: |
        # Where we expect all the cert files to reside
        CERTPATH={{ item.destination_path }}/{{ item.subject }}.{{ domain_name }}
        [ ${CERTPATH}/merged.pem -ot ${CERTPATH}/fullchain.pem ] &&
        [ ${CERTPATH}/merged.pem -ot ${CERTPATH}/privkey.pem ] &&
        cat ${CERTPATH}/fullchain.pem > ${CERTPATH}/merged.pem && cat ${CERTPATH}/privkey.pem >> ${CERTPATH}/merged.pem
      when: inventory_hostname == item.destination_host
      ignore_errors: yes
      loop: "{{ certificates }}"

    - name: Start and enable the haproxy service
      systemd:
        name: haproxy
        state: restarted
        enabled: yes
