# Playbook to configure all Exchange 2019 mail servers
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: Jun/04/2020
# -------------------------------------------------------------------------------------------------
- hosts: mail_servers
  name: Configure SQL Servers
  vars_files:
    - "{{ playbook_dir }}/passwords.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  vars:
    ansible_connection: winrm
    ansible_user: Administrator
    ansible_password: "{{ win_local_password }}"
    ansible_winrm_transport: ntlm
    ansible_port: 5985
  tasks:
    - name: Join server to domain
      win_domain_membership:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: "{{ domain_admin_user }}@{{ domain_name }}"
        domain_admin_password: "{{ domain_admin_password }}"
        domain_ou_path: "{{ server_ou }}"
        state: domain
      register: join_domain

    - name: Reboot server when joining domain
      win_reboot:
      when: join_domain.reboot_required

    - name: Get Exchange 2019 installation disc drive letter
      win_shell: Get-CimInstance Win32_LogicalDisk | ?{ $_.DriveType -eq 5 -and $_.VolumeName -eq 'SqlSetup_x64_ENU' } | % {$_.DeviceID}
      register: drive_output

    - name: Install Exchange 2019 from mounted ISO
      win_package:
        path: "{{ drive_output }}\setup.exe"
        product_id: '{0FB552DD-543E-48E7-A6F4-2F8D82723C6A}'
        arguments: >
          /IACCEPTSQLSERVERLICENSETERMS /ACTION="Install" /FEATURES=SQLEngine,Replication,Conn /INSTANCENAME="HARAMCODB"
          /SQLSYSADMINACCOUNTS="Haramco\Administrator" /SQLCOLLATION="Latin1_General_CI_AS" /qs
        state: present
