# Playbook to configure all Exchange 2019 mail servers
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: Jun/04/2020
# -------------------------------------------------------------------------------------------------
- hosts: mail_servers
  name: Join Exchange Servers to Domain
  vars_files:
    - "{{ playbook_dir }}/passwords.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  vars:
    ansible_connection: winrm
    ansible_user: Administrator
    ansible_password: "{{ win_local_password }}"
    ansible_winrm_transport: ntlm
    ansible_port: 5985
  tasks:
    - include_tasks: join_domain.yml
      vars:
        machine_ou: "{{ exchange_ou }}"

- hosts: mail_servers
  name: Configure Exchange Servers
  vars_files:
    - "{{ playbook_dir }}/passwords.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  vars:
    ansible_connection: winrm
    ansible_user: Administrator@{{ domain_name }}
    ansible_password: "{{ domain_admin_password }}"
    ansible_winrm_transport: credssp
    ansible_port: 5985
  tasks:
    - name: Install RSAT tools to allow for PrepareAD
      win_feature:
        name: RSAT-ADDS-Tools
        state: present

    - name: Install RSAT PowerShell module to check if schema was already extended
      win_feature:
        name: RSAT-AD-PowerShell
        state: present

    - name: Get Exchange 2019 installation disc drive letter
      win_shell: Get-CimInstance Win32_LogicalDisk | ?{ $_.DriveType -eq 5 -and $_.VolumeName -eq 'EXCHANGESERVER2019-X64' } | % {$_.DeviceID}
      register: drive_output

    - name: Check if Active Directory already prepared
      win_shell: |
        $schemaPath = (Get-ADRootDSE).schemaNamingContext
        $match = Get-ADObject -Filter 'Name -eq "ms-Exch-Schema-Version-Pt"' -SearchBase $schemaPath -Properties lDAPDisplayName
        if ($match -ne $null) { return "Schema Extended" }
      register: schema_extended

    - name: Run schema extension command
      win_shell: setup.exe /IAcceptExchangeServerLicenseTerms /PrepareAD /OrganizationName:{{ orgname }}
      args:
        chdir: "{{ drive_output }}"
        executable: cmd
      when: schema_extended.stdout != 'Schema Extended'

    - name: Create folder for prerequisite installers
      file:
        path: C:\Installers
        state: directory

    - name: Copy prerequisite installers
      win_copy:
        src: \\{{ domain_name }}\Shares\{{ item }}
        dest: C:\Installers
      loop:
        - UcmaRuntimeSetup.exe
        - vcredist_x64.exe

    #- name: Install Exchange 2019 from mounted ISO
      #win_package:
        #path: "{{ drive_output }}\setup.exe"
        #product_id: '{0FB552DD-543E-48E7-A6F4-2F8D82723C6A}'
        #arguments: >
          #/IAcceptExchangeServerLicenseTerms /Mode:Install /Roles:Mailbox /PrepareAD
          #/InstallWindowsComponents
        #state: present
