# Playbook to install squid forward proxy. Default configuration will suffice (port 3128; all
# 10.x.x.x machines allowed).
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: Jun/02/2020
# -------------------------------------------------------------------------------------------------
- import_playbook: allocate_host_variables.yml

- hosts: proxy_servers
  name: Install and configure the squid proxy server
  vars_files:
    - "{{ playbook_dir }}/vault.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  vars:
    ansible_user: root
    ansible_password: "{{ linux_local_password }}"
  tasks:
    - name: Install squid
      dnf:
        name: squid
        state: present

    - name: Open squid firewall port
      firewalld:
        port: 3128/tcp
        permanent: yes
        state: enabled
        zone: public

    - name: Start and enable the squid service
      systemd:
        name: squid
        state: started
        enabled: yes
