# Playbook to configure the UEM environment
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: May/30/2021
# -------------------------------------------------------------------------------------------------
- import_playbook: allocate_host_variables.yml

- hosts: "{{ groups['databases'] | first }}"
  name: Get REST API key
  vars_files:
    - "{{ playbook_dir }}/vault.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  vars:
    ansible_connection: winrm
    ansible_user: Administrator@{{ domain_name }}
    ansible_password: "{{ domain_admin_password }}"
    ansible_winrm_transport: credssp
    ansible_port: 5985
  tasks:
    - name: Get admin REST API key
      win_shell: >
        Invoke-Sqlcmd -Query "SELECT APIKey FROM dbo.APIKey WHERE ServiceName = 'AirWatchAPI'" -ServerInstance MainAG
        -Database uemdb -OutputSqlErrors 1 -AbortOnError -querytimeout 300 | ConvertTo-Json
      register: apikey
      no_log: yes

    - set_fact:
        uem_api_key: "{{ (apikey.stdout | from_json).APIKey }}"

- hosts: localhost
  connection: local
  name: Create tunnel configuration
  vars_files:
    - "{{ playbook_dir }}/vault.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  tasks:
    - set_fact:
        uem_api_key: "{{ hostvars[groups['databases'] | first]['uem_api_key'] }}"

    - name: Get global Organization Group UUID
      uri:
        url: https://uds.{{ domain_name }}/api/system/groups/7
        user: administrator
        password: "{{ uem_api_password }}"
        force_basic_auth: yes
        method: GET
        validate_certs: no
        headers:
          aw-tenant-code: "{{ uem_api_key }}"
          Accept: application/json
      register: global_group_response

    - name: Get customer Organization Group UUID
      uri:
        url: https://uds.{{ domain_name }}/api/system/groups/570
        user: administrator
        password: "{{ uem_api_password }}"
        force_basic_auth: yes
        method: GET
        validate_certs: no
        headers:
          aw-tenant-code: "{{ uem_api_key }}"
          Accept: application/json
      register: org_id_response

    - name: Get existing Site URLs configuration
      uri:
        url: https://uds.{{ domain_name }}/api/system/systemcode/siteurls
        user: administrator
        password: "{{ uem_api_password }}"
        force_basic_auth: yes
        method: GET
        validate_certs: no
        headers:
          aw-tenant-code: "{{ uem_api_key }}"
          Accept: application/json
      register: site_urls_response

    - name: Replace OG UUID in tunnel configuration file
      template:
        src: configurations/uem/tunnel-template.json
        dest: configurations/uem/tunnel.json

    - name: Replace OG UUID in site URLs configuration file
      template:
        src: configurations/uem/site-urls-template.json
        dest: configurations/uem/site-urls.json

    - name: Enable AWCM
      uri:
        url: https://uds.{{ domain_name }}/api/system/systemcode/siteurls
        user: administrator
        password: "{{ uem_api_password }}"
        force_basic_auth: yes
        method: POST
        validate_certs: no
        headers:
          aw-tenant-code: "{{ uem_api_key }}"
        status_code: 204
        body: "{{ lookup('file', 'configurations/uem/site-urls.json') }}"
        body_format: json
      when: site_urls_response.json.airwatchCloudMessaging is None

    - name: Get existing Tunnel configuration
      uri:
        url: https://uds.{{ domain_name }}/api/mdm/tunnel/configurations?group-uuid={{ org_id_response.json.Uuid }}
        user: administrator
        password: "{{ uem_api_password }}"
        force_basic_auth: yes
        method: GET
        validate_certs: no
        headers:
          aw-tenant-code: "{{ uem_api_key }}"
          Accept: application/json
        status_code: [200, 404]
      register: tunnel_config_response

    - name: Replace OG UUID in tunnel configuration file
      template:
        src: configurations/uem/tunnel-template.json
        dest: configurations/uem/tunnel.json

    - name: Create Tunnel configuration
      shell: >
        curl -X "POST" "https://uds.{{ domain_name }}/api/mdm/tunnel/configurations" -u administrator:{{ uem_api_password }}
        -H "aw-tenant-code: {{ uem_api_key }}" -k --form 'tunnelConfig=@configurations/uem/tunnel.json'
      when: tunnel_config_response.status == 404
