# Playbook to configure Workspace ONE UEM console server
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: Sep/19/2020
# -------------------------------------------------------------------------------------------------
- import_playbook: allocate_host_variables.yml
- import_playbook: web_servers.yml

- hosts: windows:&web_servers
  name: Deploy Windows IIS servers
  vars_files:
    - "{{ playbook_dir }}/vault.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  tasks:
    - name: Get Workspace ONE UEM installation disc drive letter
      win_shell: Get-CimInstance Win32_LogicalDisk | ?{ $_.DriveType -eq 5 -and $_.VolumeName -eq '20.5.0.5_Full_Install' } | % {$_.DeviceID}
      register: drive_output

    - name: Copy prerequisite installers
      win_copy:
        src: \\{{ domain_name }}\Shares\domain\{{ item }}
        dest: C:\Installers\{{ item }}
        remote_src: yes
      loop:
        - UEM\sqlncli.msi
        - UEM\vcredist_x64.exe
        - UEM\VC_redist.x64.exe

    - name: Copy installation files to Temp folder
      win_copy:
        src: \\{{ domain_name }}\Shares\domain\{{ item }}
        src: "{{ drive_output.stdout | trim }}\\Application"
        dest: C:\Installers\{{ item }}
        remote_src: yes

    - name: Install BranchCache feature
      win_feature:
        name: BranchCache
        state: present
      register: branch_feature

    - name: Install URL Rewrite 2.1
      win_package:
        path: C:\Installers\UcmaRuntimeSetup.exe
        product_id: '{A41CBE7D-949C-41DD-9869-ABBD99D753DA}'
        arguments: /quiet /norestart
        state: present

    - name:
