# Playbook to deploy all Tunnel UAG appliances
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: May/10/2021
# -------------------------------------------------------------------------------------------------
- import_playbook: allocate_host_variables.yml

- hosts: uem_tunnel_relay:uem_tunnel_endpoint
  connection: local
  name: Create Infrastructure Servers
  vars_files:
    - "{{ playbook_dir }}/vault.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  tasks:
    - name: Create directory for OVA files
      file:
        path: /var/ova
        state: directory
    - name: Download UAG appliance OVA file
      get_url:
        url: 'https://d1drul0h659ga0.cloudfront.net/euc-uag-2103.ova'
        dest: /var/ova/euc-uag-2103.ova
    - name: Create Windows virtual machines
      community.vmware.vmware_deploy_ovf:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        resource_pool: "{{ resource_pool }}"
        folder: "/{{ datacenter_name }}/vm/{{ workload_folder }}"
        name: "{{ userid }}-{{ inventory_hostname }}"
        ovf: /var/ova/euc-uag-2103.ova
        datastore: "{{ workload_datastore }}"
        networks: "{'Internet':'{{ network_name }}', 'ManagementNetwork':'{{ network_name }}', 'BackendNetwork':'{{ network_name }}'}"
        validate_certs: no
        power_on: no
        properties:
          settingsJSON: '{\"kerberosKeyTabSettingsList\":{ \"kerberosKeyTabSettings\": []}, \"kerberosRealmSettingsList\":{ \"kerberosRealmSettingsList\": []}, \"idPExternalMetadataSettingsList\":{ \"idPExternalMetadataSettingsList\": []}, \"customExecutableList\": { \"customExecutableList\": [ ]}, \"edgeServiceSettingsList\":{ \"edgeServiceSettingsList\": [{ \"identifier\": \"TUNNEL_GATEWAY\",\"airwatchComponentsInstalled\":\"TUNNEL\",\"enabled\": true,\"proxyDestinationUrl\": \"https://null\",\"apiServerUrl\": \"https://uds.{{ domain_name }}\",\"apiServerUsername\": \"apiuser\",\"apiServerPassword\": \"{{ uem_api_password }}\",\"organizationGroupCode\": \"{{ orgname }}\",\"airwatchServerHostname\": \"10.43.71.250\",\"airwatchAgentStartUpMode\": \"install\"}] }, \"systemSettings\":{\"locale\": \"en_US\",\"ssl30Enabled\": \"false\",\"tls10Enabled\": \"false\",\"tls11Enabled\": \"false\",\"tls12Enabled\": \"true\",\"tls13Enabled\": \"true\"}, \"authMethodSettingsList\":{ \"authMethodSettingsList\": [] }, \"serviceProviderMetadataList\": { \"items\": [ ] }, \"identityProviderMetaData\": {  } }'
          rootPassword: "{{ linux_local_password }}"
          adminPassword: "{{ linux_local_password }}"
          ceipEnabled: "False"
          defaultGateway: "{{ network_gateway }}"
          DNS: "{{ groups['domain_controllers'] | map('extract', hostvars, 'host_address') | map('regex_replace', '(\\d+)', network_subnet + '.\\1') | join(' ') }}"
          dnsSearch: "{{ domain_name }}"
          ip0: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
          ipMode0: STATICV4
          netmask0: "{{ network_mask }}"
          uagname: "{{ userid }}-{{ inventory_hostname }}"
      delegate_to: localhost
