# Playbook to deploy all Tunnel UAG appliances
# Written by: Hani Audah <ht.aramco@gmail.com>
# Created on: May/10/2021
# -------------------------------------------------------------------------------------------------
- import_playbook: allocate_host_variables.yml

- hosts: localhost
  connection: local
  name: Create Infrastructure Servers
  vars_files:
    - "{{ playbook_dir }}/vault.yml"
    - "{{ playbook_dir }}/strings.yml"
    - "{{ playbook_dir }}/customizations.yml"
  tasks:
    - name: Create directory for OVA files
      file:
        path: /var/ova
        state: directory
    - name: Download UAG appliance OVA file
      get_url:
        url: 'https://d1drul0h659ga0.cloudfront.net/euc-uag-2103.ova'
        dest: /var/ova/euc-uag-2103.ova
    - name: Create Windows virtual machines
      community.vmware.vmware_deploy_ovf:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        resource_pool: "{{ resource_pool }}"
        folder: "/{{ datacenter_name }}/vm/{{ workload_folder }}"
        ovf: /var/ova/euc-uag-2103.ova
        datastore: "{{ workload_datastore }}"
        networks:
          uag-network: "{{ network_name }}"
